version: '3'
services:
  web:
    image: nginx:alpine
    container_name: web
    volumes:
      - .:/usr/share/nginx/html  # Mount the current directory to Nginx's default HTML directory
    ports:
      - "80:80"  # Expose port 80 to access the web app in the browser
    restart: always
