version: '3.8'
services:
  nginx:
    build: .
    container_name: nginx
    restart: always
    ports:
      - "8080:80"  # Mapping port 80 in the container to 8080 on the host
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # Mounting the Nginx config
      - ./html:/usr/share/nginx/html  # Mounting your HTML directory
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
